### ISSUE TITLE
Titeltexten ser för liten ut på mobilen

### ISSUE THREAD

**Issue by svaret** [svaret/yfitops#27]

**Comment by svaret** [comment]
@supergillie i master är texten fortfarande liten 
på supergillie.pythonanywhere ser det bra ut

**Comment by svaret** [comment]
![C140B50F-7A1D-4896-BF75-688600CABBDA](https://user-images.githubusercontent.com/53701/210233280-4f54d340-15cd-43cd-9abd-b5673bea6478.png)

**Comment by supergillie** [comment]
Dom här raderna styr storleken vad jag förstår:
  https://github.com/svaret/yfitops/blob/d2b2f9e95ca571a852f41ad38323f4930f93099d/static/style.css#L48
https://github.com/svaret/yfitops/blob/d2b2f9e95ca571a852f41ad38323f4930f93099d/static/style.css#L63

och borde vara rätt nu

senaste på hammar.by:
<img width="905" alt="Screenshot 2023-01-02 at 15 19 52" src="https://user-images.githubusercontent.com/209369/210243693-c5ad1042-80e7-4680-a7aa-d579486d402e.png">
och på supergillie:
<img width="808" alt="Screenshot 2023-01-02 at 14 13 25" src="https://user-images.githubusercontent.com/209369/210243768-30764af2-b66f-4625-9369-8affc98be2d4.png">
