### ISSUE TITLE
yfitops-bild har försvunnit

### ISSUE THREAD

**Issue by supergillie** [svaret/yfitops#28]
trasig yfitops-länk
<img width="1330" alt="Screenshot 2023-01-01 at 17 57 56" src="https://user-images.githubusercontent.com/209369/210178821-159a000c-1f21-4f51-ad6f-2413045a77ad.png">

**Comment by svaret** [comment]
Kolla nu då @supergillie

**Comment by supergillie** [comment]
ser bra ut nu
