### ISSUE TITLE
automatisera mera

### ISSUE THREAD

**Issue by supergillie** [svaret/yfitops#3]
**den här behövs om man ska köra gitpod**
gitpod /workspace/yfitops (master) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> python app.py
> }
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import discogs_client
**ModuleNotFoundError: No module named 'discogs_client'
gitpod /workspace/yfitops (master) $** 

### Jag lyckades få det att funka lokalt genom att köra

-  pip install discogs-client
-  export PATH=$PATH:/Users/pekr/Library/Python/3.8/bin

**Comment by svaret** [comment]
Vi har issue på detta i Project-vyn
